language: scala
os: linux
jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.sbt/
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier

script:
  - sbt scalafmtCheckAll
  - sbt +compile +test

branches:
  only:
  - main
