name: Cucumber Scala CI

permissions: {}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/**

jobs:
  build:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java:
          - 17
          - 21
          - 25
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Cache sbt
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - name: Set up JDK
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8

    - name: Formatting check
      run: sbt scalafmtCheckAll

    - name: Run tests
      run: sbt +compile +test

