name: Release scala package

permissions: {}

on:
  push:
    branches:
      - release/*

jobs:
  publish-sbt:
    name: Publish scala package
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: "17"

      - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1

      - uses: cucumber/action-publish-sbt@3ab9a6d1d2eecf0a2f1bc7ac7f7e487848566ce1 # v1.0.3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: ${{ secrets.SONATYPE_USERNAME }}
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
