name: Release scala package

on:
  push:
    branches:
      - release/*

jobs:
  publish-sbt:
    name: Publish scala package
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: "17"

      - uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1.1.19

      - uses: cucumber/action-publish-sbt@38eca71785261ae2763630bf0c2f551365263600 # v1.0.2
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: ${{ secrets.SONATYPE_USERNAME }}
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
