name: Version policy check

permissions: {}

on:
  pull_request:
    branches:
    - main

jobs:
  versionpolicycheck:
    name: Version policy check
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java:
          - 21
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Cache sbt
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Set up JDK
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - uses: sbt/setup-sbt@66fb4376e81982c7d92a4074170846fff88e2e30 # v1.5.0

      - name: Version check
        run: sbt "project cucumberScala" versionPolicyCheck
