name: Version policy check

permissions: {}

on:
  pull_request:
    branches:
    - main

jobs:
  versionpolicycheck:
    name: Version policy check
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java:
          - 21
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Cache sbt
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0

      - name: Version check
        run: sbt "project cucumberScala" versionPolicyCheck
